Namespace Common
    Public Class TableNames
        Public Const Account As String = "Account"
        Public Const Address As String = "Address"
        Public Const ContactNotes As String = "ContactNotes"
        Public Const Contacts As String = "Contacts"
        Public Const DeliveryMethod As String = "DeliveryMethod"
        Public Const Discount As String = "Discount"
        Public Const DiscountCondition As String = "DiscountCondition"
        Public Const DiscountValues As String = "DiscountValues"
        Public Const Events As String = "Events"
        Public Const EventTypes As String = "EventTypes"
        Public Const Form As String = "Form"
        Public Const FormField As String = "FormField"
        Public Const FormType As String = "FormType"
        Public Const kpi2 As String = "kpi2"
        Public Const KpiGroups As String = "KpiGroups"
        Public Const KpiGroupVersions As String = "KpiGroupVersions"
        Public Const KpiInfo As String = "KpiInfo"
        Public Const KpiTypes As String = "KpiTypes"
        Public Const KpiTypes2 As String = "KpiTypes2"
        Public Const KpiVersions As String = "KpiVersions"
        Public Const OptionInfo As String = "OptionInfo"
        Public Const Order As String = "Order"
        Public Const OrderItem As String = "OrderItem"
        Public Const Price As String = "Price"
        Public Const Product As String = "Product"
        Public Const ProductCategory As String = "ProductCategory"
        Public Const ProductStats As String = "ProductStats"
        Public Const ReportParameters As String = "ReportParameters"
        Public Const Reports As String = "Reports"
        Public Const ReportSql As String = "ReportSql"
        Public Const Role As String = "Role"
        Public Const RoleToID As String = "RoleToID"
        Public Const Stock As String = "Stock"
        Public Const Supplier As String = "Supplier"
        Public Const TableVersionsConfig As String = "TableVersionsConfig"
        Public Const Target As String = "Target"
        Public Const TargetTypes As String = "TargetTypes"
        Public Const Template As String = "Template"
        Public Const Test As String = "Test"
        Public Const UserAccounts As String = "UserAccounts"
        Public Const UserRoles As String = "UserRoles"
        Public Const Users As String = "Users"
        Public Const UserToID As String = "UserToID"
        Public Const Visit As String = "Visit"
    End Class
End Namespace

